# -*- coding: utf-8 -*-
"""2021_YT_chat_streaming_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UXp6giI66IWI78MQSaZe0_LNz5UHcMew
"""

!pip install pytchat
!pip install google-cloud-pubsub

import time
import pytchat
import json
from google.cloud import pubsub_v1
from time import sleep
import os

credential_path = "/content/substantial-art-374705-bb95d1f58737.json"
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credential_path

chat = pytchat.create(video_id="ecHbnqUuqeE")

project_id = "substantial-art-374705"
topic_id = "projects/substantial-art-374705/topics/dota2_pub_1"

publisher = pubsub_v1.PublisherClient()
#topic_path = publisher.topic_path(project_id, topic_id)

while chat.is_alive():
  for c in chat.get().sync_items():
    
      data={"source":"T21","time":c.datetime,"author":c.author.name,"message":c.message}
      data=json.dumps(data).encode('utf-8')
      future = publisher.publish(topic_id, data)

      print(data)
      print(future.result())

