# -*- coding: utf-8 -*-
"""2022_YT_chat_streaming_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zmUzV5XIr0yEN5s3y-lmn-pq66gmcp7x
"""

!pip install pytchat
!pip install google-cloud-pubsub

!pip install pytchat
!pip install google-cloud-pubsub
 # Import library
import time
import pytchat
import json
from google.cloud import pubsub_v1
from time import sleep
import os

 # Connect with google Pub/Sub
credential_path = "/content/substantial-art-374705-bb95d1f58737.json"
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credential_path

# Sream comment data on 
chat = pytchat.create(video_id="UhQmAfzaw7c")

project_id = "substantial-art-374705"
topic_id = "projects/substantial-art-374705/topics/dota2_pub_2"

publisher = pubsub_v1.PublisherClient()

while chat.is_alive():
  for c in chat.get().sync_items():
    
      data={"source":"T22","time":c.datetime,"author":c.author.name,"message":c.message}
      data=json.dumps(data).encode('utf-8')
      future = publisher.publish(topic_id, data)

      print(data)
      print(future.result())

